### ISSUE TITLE
Migrate pagerduty_util modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#113]
modules/pagerduty_util.py
states/pagerduty_schedule.py
states/pagerduty_service.py
states/pagerduty_escalation_policy.py
states/pagerduty_user.py

**Comment by nicholasmhughes** [comment]
Add to pagerduty extension

**Comment by lkubb** [comment]
https://github.com/salt-extensions/extension_migration/issues/112
