### ISSUE TITLE
Migrate redismod modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#134]
modules/redismod.py
pillar/redismod.py
states/redismod.py

**Comment by nicholasmhughes** [comment]
Extension Name: saltext-redis

**Comment by nicholasmhughes** [comment]
@jheiselman Yes. All Redis-related modules have been consolidated here: https://github.com/salt-extensions/saltext-redis

We'll get a release out pretty soon so folks can start kicking the tires.

**Comment by lkubb** [comment]
It's already migrated and has a release.
