### ISSUE TITLE
Dry Run results need to be more explicit as to whether it is a success or failure

### ISSUE THREAD

**Issue by snelzing** [salt-extensions/extension_migration#186]
![image](https://github.com/salt-extensions/extension_migration/assets/39928924/c90de01c-b4b7-48f4-bbb3-b13408e510b7)

When you perform the dry run, it dumps a bunch of text when it is finish and nothing signifies whether it succeeded or failed. 

Someone new to the project may get confused.

**Comment by garethgreenaway** [comment]
Fixed with https://github.com/salt-extensions/extension_migration/pull/194
