### ISSUE TITLE
Migrate haproxyconn modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#48]
modules/haproxyconn.py
beacons/haproxy.py

**Comment by nicholasmhughes** [comment]
Extension Name: saltext-haproxy

**Comment by nicholasmhughes** [comment]
- [ ] copier profile 0.0.2
- [ ] copier profile 0.2.7
- [ ] make `pre-commit run -a` clean
- [ ] make `nox -e docs` run clean
- [ ] make `nox -e tests-3 -- -vvv tests/` run clean 
- [ ] update CHANGELOG for 1.0.0
- [ ] tag v1.0.0

**Comment by lkubb** [comment]
I performed all those steps already: https://github.com/salt-extensions/saltext-haproxy
