### ISSUE TITLE
Migrate helm modules to extension

### ISSUE THREAD

**Issue by garethgreenaway** [salt-extensions/extension_migration#50]
modules/helm.py
states/helm.py

**Comment by nicholasmhughes** [comment]
- [ ] copier profile 0.0.2
- [ ] copier profile 0.2.7
- [ ] make `pre-commit run -a` clean
- [ ] make `nox -e docs` run clean
- [ ] make `nox -e tests-3 -- -vvv tests/` run clean 
- [ ] update CHANGELOG for 1.0.0
- [ ] tag v1.0.0

**Comment by lkubb** [comment]
Has been finished: https://github.com/salt-extensions/saltext-helm
